version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/pxl-nodejs-framework
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/deployment/set-permissions.sh
      timeout: 300
    - location: scripts/deployment/install-and-build.sh
      timeout: 300
      runas: ec2-user
    - location: scripts/deployment/start-server.sh
      timeout: 300
      runas: ec2-user
