version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
   commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the application...
      - npm run build:minimal
      - |
        PACKAGE_FILENAME=$(npm pack | tail -1)
        echo "Package filename: $PACKAGE_FILENAME"
        echo "Copying package file..."
        cp $PACKAGE_FILENAME pxl-nodejs-framework.tgz
  post_build:
    commands:
      - echo "Build and installation completed, copy to S3..."
      - aws s3 cp --recursive ./ s3://socialamp-dev-npm/pxl-nodejs-framework/ --exclude "*" --include "*.tgz" --acl private --metadata-directive REPLACE
      - echo "Copy to S3 completed."
artifacts:
  files:
    - '**/*'
  base-directory: '.'
cache:
  paths:
    - node_modules/**/*
