version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm install -g yalc
      - npm install
  build:
    commands:
      - echo "Publishing package with Yalc..."
      - yalc publish
      - cd ~/.yalc/packages
      - ls -la
      - cp ~/.yalc/packages/* ./.yalc
  post_build:
    commands:
      - echo "Build and installation completed, copying to S3..."
      - aws s3 cp --recursive .yalc/ s3://socialamp-dev-npm/pxl-nodejs-framework/ --acl private --metadata-directive REPLACE
      # - echo "Copy to S3 completed."
artifacts:
  files:
    - '**/*'
  base-directory: '.'
cache:
  paths:
    - node_modules/**/*
